### ISSUE TITLE
Thought you might like to know

### ISSUE THREAD

**Issue by domingoladron** [endjin/dotnet-adr#125]
I love your dotnet-adr tool so much, I added an article about it to my engineering blog.  

https://medium.com/it-dead-inside/architectural-decision-records-adr-with-dotnet-adr-9fa76104bcd7?source=friends_link&sk=7549ae2a650eeaa188b7318726a2eab9

Cheers

Chris Laine

**Comment by HowardvanRooijen** [comment]
Excellent!

I'm working on updating the app and dependencies, and adding a little bit of polish - but I'm really glad you've blogged about this. We'll amplify!

**Comment by domingoladron** [comment]
That's amazing.  Let me know when the new version is available, and I'll update my article accordingly.

Cheers

**Comment by chrissmithptml** [comment]
Hey, did you guys ever get around to pushing your changes to this?  Just checking in.

**Comment by HowardvanRooijen** [comment]
Hi! I've just pushed up the changes I've been working on and released a [v1.1.0](https://www.nuget.org/packages/adr/). If you check out this repo, you should see an expanded [readme](https://github.com/endjin/dotnet-adr/blob/main/README.md) with lots more context / info. I've also added a [community contributions](https://github.com/endjin/dotnet-adr/blob/main/README.md#community-contributions) section.

**Comment by domingoladron** [comment]
Ah, cheers, mate!  Much appreciated!  I'll close this off now.
