### ISSUE TITLE
I'm getting an "Object reference not set to an instance of an object." when I try to use adr new

### ISSUE THREAD

**Issue by rodrigojuarez** [endjin/dotnet-adr#174]
On a clean computer, trying to run the commands like in the TLDR section will return the error when I try to use ```adr new "test"```

![image](https://github.com/endjin/dotnet-adr/assets/788727/7b4095a6-051d-42f0-8422-ec0b4ba9edea)

![image](https://github.com/endjin/dotnet-adr/assets/788727/1c65c8ae-fdd0-4645-90a9-af453610690a)

Please let me know if you need any additional information

**Comment by HowardvanRooijen** [comment]
I can only apologise... let me investigate!

**Comment by HowardvanRooijen** [comment]
Ah OK. I've spotted an issue. The tool assumes you're in a folder structure that's part of a git repo. If you're just using it in a folder, like "adr" it will blow up. I'll add a fix - thanks for useful repro steps!

**Comment by rodrigojuarez** [comment]
I can confirm that it works as expected if you are inside a folder that is part of a git repo

**Comment by HowardvanRooijen** [comment]
That should be fixed in v1.1.4 which is available on nuget.org. Thanks for all the feedback - much appreciated. ♥️
