### ISSUE TITLE
Supersede using the MADR template

### ISSUE THREAD

**Issue by jamesbellerue** [endjin/dotnet-adr#190]
Trying to supersede a decision when using the MADR template doesn't appear to update the original decision status.

example:
adr templates set madr
adr new decision1
adr new decision2 -i 1

decision2 gets created, and the output from adr indicates "Superseded ADR record; 1" but 0001-decision1.md is not updated with the superseded status.

I think the status in the template isn't matching the regex used to search for the status in NewAdrCommand.cs,  If Status is a level 2 heading ( ## Status) then the supersede works correctly.

**Comment by HowardvanRooijen** [comment]
Thanks for reporting - I'll take a look!
