### ISSUE TITLE
Use docs\adr folder automatically for all commands, not just init

### ISSUE THREAD

**Issue by idg10** [endjin/dotnet-adr#20]
If you run this command from the root folder of your repo:

`adr init`

it will add a new subfolder, `docs\adr`, which is the standard place for ADR records to live. If you then run the following command without changing the current directory:

`adr new "Tabs vs spaces"`

This will not add the new entry in `docs\adr`. Instead it will put it in the folder you're currently in.

Unless there's some good reason not to, we should consider making the various commands consistently presume that `docs\adr` is the place for ADR records by default.

We might want to consider whether it's worth being clever enough to walk up the folder heirarchy (stopping at the folder containing the `.git` subfolder) to locate the `docs\adr` folder automatically even if you're in a subfolder at the time.

**Comment by SecretDeveloper** [comment]
Would it be better to drop the "docs/adr" convention and instead use the current directory?

If we continue to use convention then we need to check where we are each time we run a command and it only works as expected currently if you are at the project root.

I'd prefer to just cd to the where I keep the adr files when creating them rather, or provide a path parameter to skip changing directories...

**Comment by chrissmithptml** [comment]
I personally think using the docs/adr directory is a good convention, as it means I always know to go look for adr records in the same locale.  Making it loose and just putting adr records anywhere I am when I run the command seems a bit too loose.

**Comment by HowardvanRooijen** [comment]
You can now [set your own convention](https://github.com/endjin/dotnet-adr#configure-the-default-adr-location-in-your-repo), or supply a path or use the current path.
